#include <stdexcept>
#include <string>
#include <iostream>
#include <sstream>
#include <math.h>
#include <algorithm>
#include <bitset>
#include "..\Exceptions.h"
#include "..\Vector\IVector.h"
#include "..\Vector\Vector.h"
#include "..\CRTP.h"
#include "IMatrix.h"
